include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true # Prevents hidden dynamic casts
    strict-inference: true # Forces type clarity
    strict-raw-types: true # Prevents raw List/Map usage
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    # Your existing rules
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_declare_return_types: true
    annotate_overrides: true
    curly_braces_in_flow_control_structures: true

    # Additional recommended rules
    # Code style
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    # Error prevention
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    empty_catches: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    throw_in_finally: true

    # Code clarity
    avoid_bool_literals_in_conditional_expressions: true
    avoid_function_literals_in_foreach_calls: true
    avoid_redundant_argument_values: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_void_to_null: true
    unnecessary_this: true

    # Performance
    avoid_unnecessary_containers: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true

    # Package health
    depend_on_referenced_packages: true
    package_names: true
    use_full_hex_values_for_flutter_colors: true